### ISSUE TITLE
Graphs are not the same when switching tabs.

### ISSUE THREAD

**Issue by brianmcmichael** [AweSim-OSC/osc-systemstatus#47]
When I click one of the duration tabs, ("2 hours", "4 Hours", etc.) the graphs revert to the default for the page, rather than the one I was last looking at.

I think that earlier versions of this app allowed for a user to quickly switch tabs while viewing the same chart type, but it's possible that this has always behaved this way. 

Ideally, if I am looking at a large "Moab Nodes Report" for example, and then switch to another duration tab, I'd be looking at the "Moab Nodes Report" for that timespan.

**Comment by ericfranz** [comment]
@AriettaZ is there a clear, simple way to accomplish this with the current code? It seems like we need some type of "current graph" variable and show this when selecting the graph. If it isn't an easy, simple fix, don't do it, because we can wait till #54 is done which will make this easy to implement.
